### PR TITLE
Share btn

### PR DESCRIPTION
**Pull request by srollins01**
### Details
Share button for event details page / popover for social media links. 
**Note- temporary placeholder URL added for Facebook and Line sharing (valid URL for our site is necessary).

### Added Libraries
react-share and react-popper @popperjs/core.

### CODE REVIEW

**Review by Paulette-Zaldivar-Flores — CHANGES_REQUESTED** [review]
hi @srollins01 I like the links and how the new copy, facebook and line buttons are styled. However, I think that usually when pressing on a copy icon it will usually go from copy to copied without a pop up window. In addition, I think that the most common ways of sharing links these days do not include LINE or Facebook. Usually email and or QR code are most common in addition to copying the link directly. I think that for the purpose of this project the copy and email would suffice. What do you think?

**Comment by Paulette-Zaldivar-Flores** [comment]
https://github.com/Paulette-Zaldivar-Flores/Friendster/assets/96970580/9d6bf259-f366-4a33-a9fb-12f4fe33d1cc

**Comment by srollins01** [comment]
Hi @Paulette-Zaldivar-Flores,
Sure! I agree. I'll go ahead and make those changes soon.

**Comment by srollins01** [comment]
Hi @Paulette-Zaldivar-Flores, I've completed the changes. Could you please review the new commits? Thanks!

**Review by Paulette-Zaldivar-Flores — CHANGES_REQUESTED** [review]
@srollins01 I can't run your branch as I am getting that warning that you talked baout earlier this week. Can you run it on your end ok?

**Pull request merged**
